#!/usr/bin/env python3
"""
Git Hook Installer

Generated by Cursor Agent Factory

Installs pre-commit hook that runs validation before commits.
Cross-platform support for Unix and Windows.

Usage:
    python scripts/git/install_hooks.py
"""

import argparse
import os
import stat
import sys
from pathlib import Path


# Pre-commit hook script content
PRE_COMMIT_HOOK = """#!/bin/sh
# Pre-commit hook generated by Cursor Agent Factory

# Secret scan (blocks commit if secrets found)
if [ -f "scripts/guardian/secret_scanner.py" ]; then
    python3 scripts/guardian/secret_scanner.py --check
    if [ $? -ne 0 ]; then
        echo "❌ Secret scan failed. Commit blocked."
        exit 1
    fi
fi

# JSON validation (blocks commit if invalid JSON)
if [ -f "scripts/git/pre_commit_runner.py" ]; then
    python3 scripts/git/pre_commit_runner.py --check --fast
    if [ $? -ne 0 ]; then
        echo "❌ Pre-commit validation failed. Commit blocked."
        exit 1
    fi
fi

# Run full pre-commit runner in sync mode
if [ -f "scripts/git/pre_commit_runner.py" ]; then
    python3 scripts/git/pre_commit_runner.py --sync
fi

exit 0
"""


# Windows batch script version
PRE_COMMIT_HOOK_WINDOWS = """@echo off
REM Pre-commit hook generated by Cursor Agent Factory

REM Secret scan (blocks commit if secrets found)
if exist "scripts\\guardian\\secret_scanner.py" (
    python scripts\\guardian\\secret_scanner.py --check
    if errorlevel 1 (
        echo ❌ Secret scan failed. Commit blocked.
        exit /b 1
    )
)

REM JSON validation (blocks commit if invalid JSON)
if exist "scripts\\git\\pre_commit_runner.py" (
    python scripts\\git\\pre_commit_runner.py --check --fast
    if errorlevel 1 (
        echo ❌ Pre-commit validation failed. Commit blocked.
        exit /b 1
    )
)

REM Run full pre-commit runner in sync mode
if exist "scripts\\git\\pre_commit_runner.py" (
    python scripts\\git\\pre_commit_runner.py --sync
)

exit /b 0
"""


def install_hook(git_dir: Path, overwrite: bool = False) -> bool:
    """
    Install pre-commit hook.
    
    Args:
        git_dir: Path to .git directory
        overwrite: If True, overwrite existing hook
        
    Returns:
        True if installed successfully
    """
    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)
    
    hook_path = hooks_dir / "pre-commit"
    
    # Check if hook already exists
    if hook_path.exists() and not overwrite:
        print(f"⚠️  Pre-commit hook already exists at {hook_path}")
        response = input("Overwrite? (y/N): ").strip().lower()
        if response != "y":
            print("Skipping hook installation")
            return False
    
    # Determine which script to use based on platform
    is_windows = os.name == "nt"
    
    if is_windows:
        hook_content = PRE_COMMIT_HOOK_WINDOWS
    else:
        hook_content = PRE_COMMIT_HOOK
    
    # Write hook file
    hook_path.write_text(hook_content, encoding="utf-8")
    
    # Make executable on Unix
    if not is_windows:
        current_mode = hook_path.stat().st_mode
        hook_path.chmod(current_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
    
    print(f"✅ Installed pre-commit hook at {hook_path}")
    return True


def uninstall_hook(git_dir: Path) -> bool:
    """
    Uninstall pre-commit hook.
    
    Args:
        git_dir: Path to .git directory
        
    Returns:
        True if uninstalled successfully
    """
    hook_path = git_dir / "hooks" / "pre-commit"
    
    if not hook_path.exists():
        print("ℹ️  No pre-commit hook found")
        return False
    
    # Check if it's our hook
    content = hook_path.read_text(encoding="utf-8")
    if "Cursor Agent Factory" not in content:
        print("⚠️  Pre-commit hook exists but doesn't appear to be from Cursor Agent Factory")
        response = input("Remove anyway? (y/N): ").strip().lower()
        if response != "y":
            return False
    
    hook_path.unlink()
    print(f"✅ Removed pre-commit hook at {hook_path}")
    return True


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Install or uninstall git pre-commit hooks"
    )
    parser.add_argument(
        "--uninstall",
        action="store_true",
        help="Uninstall existing hook"
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing hook without prompting"
    )
    parser.add_argument(
        "--root",
        type=str,
        default=".",
        help="Project root directory (default: current directory)"
    )
    
    args = parser.parse_args()
    
    root_dir = Path(args.root).resolve()
    git_dir = root_dir / ".git"
    
    if not git_dir.exists():
        print("❌ Not a git repository. Run 'git init' first.")
        return 1
    
    if args.uninstall:
        if uninstall_hook(git_dir):
            return 0
        return 1
    else:
        if install_hook(git_dir, overwrite=args.overwrite):
            return 0
        return 1


if __name__ == "__main__":
    sys.exit(main())
