#!/usr/bin/env python3
"""
Safe Commit Wrapper

Generated by Cursor Agent Factory

Runs pre-commit validation before committing. Provides a safe way to commit
with automatic validation and optional push.

Usage:
    python scripts/git/safe_commit.py "commit message"
    python scripts/git/safe_commit.py "commit message" --push
"""

import argparse
import subprocess
import sys
from pathlib import Path


def run_pre_commit(root_dir: Path) -> bool:
    """
    Run pre-commit validation.
    
    Args:
        root_dir: Project root directory
        
    Returns:
        True if validation passed
    """
    pre_commit_script = root_dir / "scripts" / "git" / "pre_commit_runner.py"
    
    if not pre_commit_script.exists():
        print("[WARN] Pre-commit runner not found. Skipping validation.")
        return True
    
    try:
        result = subprocess.run(
            [sys.executable, str(pre_commit_script), "--sync"],
            cwd=root_dir,
            capture_output=False
        )
        return result.returncode == 0
    except Exception as e:
        print(f"[FAIL] Error running pre-commit validation: {e}")
        return False


def commit(root_dir: Path, message: str) -> bool:
    """
    Create git commit.
    
    Args:
        root_dir: Project root directory
        message: Commit message
        
    Returns:
        True if commit succeeded
    """
    try:
        result = subprocess.run(
            ["git", "commit", "-m", message],
            cwd=root_dir,
            capture_output=False
        )
        return result.returncode == 0
    except Exception as e:
        print(f"[FAIL] Error creating commit: {e}")
        return False


def push(root_dir: Path) -> bool:
    """
    Push commits to remote.
    
    Args:
        root_dir: Project root directory
        
    Returns:
        True if push succeeded
    """
    try:
        result = subprocess.run(
            ["git", "push"],
            cwd=root_dir,
            capture_output=False
        )
        return result.returncode == 0
    except Exception as e:
        print(f"[FAIL] Error pushing: {e}")
        return False


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Safe commit with pre-commit validation"
    )
    parser.add_argument(
        "message",
        type=str,
        help="Commit message"
    )
    parser.add_argument(
        "--push",
        action="store_true",
        help="Push to remote after commit"
    )
    parser.add_argument(
        "--skip-validation",
        action="store_true",
        help="Skip pre-commit validation (not recommended)"
    )
    parser.add_argument(
        "--root",
        type=str,
        default=".",
        help="Project root directory (default: current directory)"
    )
    
    args = parser.parse_args()
    
    root_dir = Path(args.root).resolve()
    
    # Check if we're in a git repository
    git_dir = root_dir / ".git"
    if not git_dir.exists():
        print("[FAIL] Not a git repository. Run 'git init' first.")
        return 1
    
    # Run pre-commit validation
    if not args.skip_validation:
        print("[INFO] Running pre-commit validation...")
        if not run_pre_commit(root_dir):
            print("[FAIL] Pre-commit validation failed. Commit aborted.")
            print("   Fix the issues above or use --skip-validation to bypass (not recommended)")
            return 1
        print("[OK] Pre-commit validation passed")
    
    # Create commit
    print(f"[EDIT] Creating commit: {args.message}")
    if not commit(root_dir, args.message):
        print("[FAIL] Commit failed")
        return 1
    print("[OK] Commit created successfully")
    
    # Push if requested
    if args.push:
        print("[INFO] Pushing to remote...")
        if not push(root_dir):
            print("[FAIL] Push failed")
            return 1
        print("[OK] Pushed to remote")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
