import os
import pytest
import subprocess
from pathlib import Path

# The conftest.py provides factory_root and python_executable fixtures


def test_knowledge_audit_execution(factory_root, python_executable):
    """Verify that the knowledge audit script runs successfully and generates a report."""
    knowledge_audit_script = (
        factory_root / "scripts" / "maintenance" / "knowledge_audit.py"
    )
    health_report = factory_root / "docs" / "audits" / "KNOWLEDGE_HEALTH.md"

    # Ensure any old report is gone
    if health_report.exists():
        os.remove(health_report)

    # Run the script
    result = subprocess.run(
        [python_executable, str(knowledge_audit_script)], capture_output=True, text=True
    )

    assert result.returncode == 0, f"Script failed with stderr: {result.stderr}"
    assert health_report.exists(), "KNOWLEDGE_HEALTH.md was not generated"

    content = health_report.read_text(encoding="utf-8")
    assert "# Knowledge Health Report" in content
    assert "## 📊 Summary Metrics" in content
    assert "## 🛠️ Knowledge Debt" in content


def test_knowledge_debt_detection(factory_root):
    """Verify that knowledge debt detection identifies thin files."""
    health_report = factory_root / "docs" / "audits" / "KNOWLEDGE_HEALTH.md"

    # This test assumes the report was generated by the previous test or exists
    if not health_report.exists():
        pytest.skip("KNOWLEDGE_HEALTH.md does not exist, skipping debt detection check")

    content = health_report.read_text(encoding="utf-8")
    assert "| Type | Artifact Path | Reason |" in content
