import os
import logging
from datetime import datetime
from typing import List, Dict, Any

logger = logging.getLogger(__name__)


class ReportManager:
    """
    Handles generation of automated data science reports.
    Integrates AI insights, project metadata, and visualization references.
    """

    def __init__(self, report_dir="projects/statistical_dashboards/data/reports"):
        self.report_dir = report_dir
        if not os.path.exists(self.report_dir):
            os.makedirs(self.report_dir)

    def generate_markdown_report(
        self, project, insights: List[Dict[str, str]], datasets: List[Any]
    ) -> str:
        """
        Generates a comprehensive Markdown report.
        """
        report_title = f"Analytical Report: {project.name}"
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        lines = [
            f"# {report_title}",
            f"**Generated at:** {timestamp}",
            f"**Project Focus:** {project.description}",
            "\n---\n",
            "## 📊 Data Summary",
        ]

        if datasets:
            for ds in datasets:
                lines.append(
                    f"- **{ds.filename}**: {ds.row_count} rows, {len(ds.columns.split(',')) if ds.columns else 0} columns."
                )
        else:
            lines.append("No datasets currently associated.")

        lines.append("\n---\n")
        lines.append("## 🧠 AI-Driven Insights")

        if insights:
            for insight in insights:
                lines.append(f"### {insight.get('title', 'Observation')}")
                lines.append(insight.get("content", "No content provided."))
                lines.append("")
        else:
            lines.append("No AI insights generated for this report.")

        lines.append("\n---\n")
        lines.append("## 📝 Strategic Recommendations")
        lines.append(
            "Based on the analyzed patterns, the following actions are suggested:"
        )
        lines.append(
            "1. **Verify Anomalies**: Review the identified outliers for operational causes."
        )
        lines.append(
            "2. **Optimize Resource Allocation**: Adjust stowing targets based on the current UPH trends."
        )
        lines.append(
            "3. **Monitor Transitions**: Keep a close eye on shift change variances."
        )

        lines.append(
            "\n\n*This report was automatically generated by the Antigravity Statistical Dashboard.*"
        )

        report_content = "\n".join(lines)
        filename = f"report_{project.id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        path = os.path.join(self.report_dir, filename)

        try:
            with open(path, "w", encoding="utf-8") as f:
                f.write(report_content)
            return path
        except Exception as e:
            logger.error(f"Failed to save report: {e}")
            return f"Error: {str(e)}"
